// <auto-generated />
namespace CartoonViewer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RenameVoiceOverListInEpisodeModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameVoiceOverListInEpisodeModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201904161211291_RenameVoiceOverListInEpisodeModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
